version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mongo
    networks:
      - app-network
    env_file:
      - .env
    ports:
      - "3000:${APP_PORT}"
    volumes:
      - .:/usr/src/app

  mongo:
    image: mongo:latest
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network
    env_file:
      - .env
    ports:
      - "${DATABASE_PORT}:27017"

volumes:
  mongo-data:

networks:
  app-network:
    driver: bridge